DoStuff/Entities/TodoItem.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace DoStuff.Entities
{
    [Table("TodoItems")]
    public class TodoItem
    {
        public int Id { get; set; }

        public bool IsDone { get; set; }

        public string Content { get; set; }

        public DateTime CreatedDate { get; set; } = DateTime.Now;

        public DateTime? ModifiedDate { get; set; }

        public int ListId { get; set; }

        public TodoList TodoList { get; set; }
    }
}

DoStuff/Entities/TodoList.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace DoStuff.Entities
{
    [Table("TodoList")]
    public class TodoList
    {

        public int Id { get; set; }

        public string? Title { get; set; }

        public DateTime CreatedDate { get; set; } = DateTime.Now;

        public DateTime? ModifiedDate { get; set; }

        public List<TodoItem> TodoItems { get; set; }
    }
}

DoStuff/Models/TodoListViewModel.cs
using DoStuff.Entities;
using Microsoft.EntityFrameworkCore;

namespace DoStuff
{
    public class TodoListViewModel
    {
        public DbSet<TodoList> Lists { get; set; }
    }
}

DoStuff/Models/TodoViewModel.cs
using DoStuff.Entities;

namespace DoStuff
{
    public class TodoViewModel
    {
        public string Title { get; set; }
        public List<TodoItem> Items { get; set; }
        public int ListId { get; internal set; }
    }
}

DoStuff/Controllers/HomeController.cs
using DoStuff.Data;
using DoStuff.Entities;
using Microsoft.AspNetCore.Mvc;

namespace DoStuff.Controllers
{
    public class HomeController : Controller
    {
        private readonly TodoDbContext _context;

        public HomeController(TodoDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var model = new TodoListViewModel
            {
                Lists = _context.TodoList
            };
            return View(model);
        }

        public IActionResult Add(string title)
        {
            var list = new TodoList { Title = title };
            _context.TodoList.Add(list);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int listId)
        {
            var list = _context.TodoList.FirstOrDefault(l => l.Id == listId);
            _context.TodoList.Remove(list);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DoStuff/Controllers/TodoController.cs
using DoStuff.Data;
using DoStuff.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoStuff.Controllers
{
    public class TodoController : Controller
    {
        private readonly TodoDbContext _context;

        public TodoController(TodoDbContext context)
        {
            _context = context;
        }

        
        
        [HttpPost]
        public IActionResult Add(string content, int listId)
        {
            if(listId == 0)
            {
                var list = new TodoList { Title = "New List" };
                _context.TodoList.Add(list);
                _context.SaveChanges();
                listId = list.Id;
            }
            var item = new TodoItem { 
                Content = content,
                ListId = listId
            };
            _context.Items.Add(item);
            _context.SaveChanges();
            return RedirectToAction("Index", new { listId = listId});
        }

        public IActionResult Check(int itemId, int listId)
        {
            var item = _context.Items.First(i => i.Id == itemId);
            item.IsDone = !item.IsDone;
            _context.Items.Update(item);
            _context.SaveChanges();
            return RedirectToAction("Index", new { listId });
        }

        public IActionResult Delete(int itemId, int listId)
        {
            var item = _context.Items.First(i => i.Id == itemId);
            _context.Remove(item);
            _context.SaveChanges();
            return RedirectToAction("Index", new { listId });
        }

        public IActionResult Index(int listId)
        {
            var list = _context.TodoList.Include(l => l.TodoItems).FirstOrDefault(i => i.Id == listId);

            var model = new TodoViewModel
            {
                ListId = list?.Id ?? -1,
                Title = list?.Title ?? "Title",
                Items = list?.TodoItems.OrderByDescending(i => i.CreatedDate).ToList() ?? new List<TodoItem>()
            };
            return View(model);
        }
    }
}

DoStuff/Views/Home/Index.cshtml
@model TodoListViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "DoStuff";
}



<div class="content">
    <div class="list">
        <h3>Your List</h3>
        <form method="post" asp-action="Add" class="list-add">
            <input type="text" name="title" />
            <button><i class="fa-solid fa-plus"></i></button>
        </form>
        <div class="sort"></div>
        <div class="list-items">
            @foreach (var item in Model.Lists)
            {
                <div class="item">
                    <div class="item-body">
                        <div class="list-content"><p>@(item.Title ?? "No Title")</p></div>
                        <div class="actions">
                            <a asp-action="Delete" asp-controller="Home" asp-route-listId="@item.Id"><i class="fa-solid fa-trash icon"></i></a>
                        </div>
                        <a class="more" asp-action="Index" asp-controller="Todo" asp-route-listId="@item.Id">
                            <span>More</span>
                            <i class="fa-solid fa-angles-right"></i>
                        </a>
                    </div>
                    <div class="time">@item.CreatedDate</div>
                </div>
            }
        </div>
    </div>
</div>

DoStuff/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
        <title>Do Stuff</title>
    </head>
    <body>
        <nav>
            <a href="/"><h2>DoStuff</h2></a>
        </nav>
        @RenderBody()
        <script src="https://kit.fontawesome.com/ec9224e721.js" crossorigin="anonymous"></script>
    </body>
</html>

DoStuff/Views/Todo/Index.cshtml
@model TodoViewModel


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "DoStuff";
}

<div class="content">
    <div class="list">
        <h3>@Model.Title</h3>
        <form method="post" asp-action="Add" class="list-add">
            <input type="hidden" name="listId"  value="@Model.ListId"/>
            <input type="text" name="content" />
            <button><i class="fa-solid fa-plus"></i></button>
        </form>
        <div class="sort"></div>
        <div class="list-items">
            @{int i = 0;}
            @foreach(var item in Model.Items) {
                i++;
                <div class="item">
                    <div class="item-body">
                        <div>
                            <input type="checkbox" class="cbx" id="cbx-@i" style="display: none;" @(item.IsDone ? "checked" : "") />
                            <label for="cbx-@i" class="check">
                                <a asp-action="Check" asp-controller="Todo" asp-route-itemId="@item.Id" asp-route-listId="@Model.ListId">
                                <svg width="18px" height="18px" viewBox="0 0 18 18">
                                    <path d="M1,9 L1,3.5 C1,2 2,1 3.5,1 L14.5,1 C16,1 17,2 17,3.5 L17,14.5 C17,16 16,17 14.5,17 L3.5,17 C2,17 1,16 1,14.5 L1,9 Z"></path>
                                    <polyline points="1 9 7 14 15 4"></polyline>
                                </svg>
                            </a>
                            </label>
                        </div>
                        <div class="list-content"><p>@item.Content</p></div>
                        <div class="actions">
                            <a asp-action="Delete" asp-controller="Todo" asp-route-itemId="@item.Id" asp-route-listId="@Model.ListId"><i class="fa-solid fa-trash icon"></i></a>
                        </div>
                    </div>
                    <div class="time">@item.CreatedDate</div>
                </div>
            }
        </div>
    </div>
</div>